name = "GasphaseReactions"
uuid = "ceedd18c-cbe2-4568-b16d-0e09f1cb20d1"
authors = ["Vinod Janardhanan"]
version = "0.1.0"

[compat]
julia = "1.7.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
